sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: LlF2024!
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSLZEd4CgdMFwE9kakU
    access-key-secret: ihYpXEEOSFt2vrukPAkEBPAzof0FcK
    bucket-name: theskytakeout
  redis:
    host: localhost
    port: 6379
    database: 10

  wechat:
    app-id: wxd845415d974da7b0
    secret: 1aab23207b98fc46bcd4ae999ecffbcd